"""
Tests for value realism in generated synthetic data.

Two defects, found running the accelerator against the real IRS Form 990-T:

1. Free-text fields (PersonNm, AddressLine, CityNm, ...) whose XSD type carries a
   permissive regex pattern were generated by obeying the pattern, producing
   unreadable character soup ("2Ic u o' Hz f cAa") even though a semantic field
   hint was detected. A detected hint must now win over a permissive text pattern.

2. Numeric fields with no XSD bound (e.g. *Amt) were generated as a sequential
   0,1,2,3 ramp, and the documented `amount_ranges` parameter had no effect.
   Unbounded numerics must now spread across a realistic range.
"""
import re
import pytest


# A text field whose type has a permissive (real-MeF-style) pattern, plus an
# unbounded amount field, plus an enumeration and a strict-pattern id for the
# no-regression checks.
REALISM_XSD = """<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="Filing">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="OfficerPersonNm">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="([A-Za-z0-9'\\-] ?)*[A-Za-z0-9'\\-]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="TotalRevenueAmt" type="xsd:integer"/>
        <xsd:element name="EmployerEIN">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[0-9]{9}"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="FilingStatusCd">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="ACTIVE"/>
              <xsd:enumeration value="AMENDED"/>
              <xsd:enumeration value="FINAL"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>
"""


@pytest.fixture
def realism_df(spark, temp_xsd, notebook_classes):
    xsd_to_synthetic = notebook_classes.get("xsd_to_synthetic")
    if xsd_to_synthetic is None:
        pytest.skip("xsd_to_synthetic not available in notebook_classes")
    path = temp_xsd(REALISM_XSD)
    df = xsd_to_synthetic(
        spark,
        xsd_path=path,
        root_element="Filing",
        num_rows=60,
        verbose=True,
        auto_detect_hints=True,
        amount_ranges={r".*Amt$": (1000, 5_000_000), "default": (0, 1_000_000)},
    )
    return df.collect(), df.columns


def _col(name, columns):
    # account for possible flatten prefixing (e.g. Filing_OfficerPersonNm)
    for c in columns:
        if c == name or c.endswith("_" + name):
            return c
    return None


def test_hint_beats_permissive_text_pattern(realism_df):
    """OfficerPersonNm has a permissive pattern but a PERSON_NAME hint -> readable names."""
    rows, columns = realism_df
    col = _col("OfficerPersonNm", columns)
    assert col, f"name column not found in {columns}"
    vals = [r[col] for r in rows if r[col]]
    assert vals, "no values generated"
    # Faker names contain a space and alphabetic words; pattern soup does not.
    spaced = sum(1 for v in vals if " " in v and any(p.isalpha() for p in v.split()))
    assert spaced >= len(vals) * 0.6, f"values look like pattern soup, not names: {vals[:5]}"


def test_amount_ranges_honored_for_unbounded_numeric(realism_df):
    """TotalRevenueAmt has no XSD bound -> amount_ranges applies, values spread."""
    rows, columns = realism_df
    col = _col("TotalRevenueAmt", columns)
    assert col, f"amount column not found in {columns}"
    vals = [r[col] for r in rows if r[col] is not None]
    assert vals, "no values generated"
    assert all(1000 <= v <= 5_000_000 for v in vals), f"out of amount_ranges: {sorted(vals)[:5]}"
    # Not a 0,1,2,3 ramp: expect many distinct values.
    assert len(set(vals)) > 5, f"values look sequential, not random: {sorted(vals)[:10]}"


def test_enumeration_still_only_legal_values(realism_df):
    """Regression: enumerations must still yield only declared values."""
    rows, columns = realism_df
    col = _col("FilingStatusCd", columns)
    assert col
    legal = {"ACTIVE", "AMENDED", "FINAL"}
    assert {r[col] for r in rows if r[col]} <= legal


def test_strict_pattern_id_still_matches(realism_df):
    """Regression: a strict numeric pattern (no hint) must still match its regex."""
    rows, columns = realism_df
    col = _col("EmployerEIN", columns)
    assert col
    vals = [r[col] for r in rows if r[col]]
    assert vals and all(re.fullmatch(r"[0-9]{9}", v) for v in vals), f"EIN broke: {vals[:5]}"
